###

GET  http://localhost:4000/api/employees

###

POST  http://localhost:4000/api/employees
Content-Type: application/json

{

"name":"Ryan Ray",
"position":"Snr. Developer",
"office":"Rome",
"salary":"22000"



}
###